name: Update Zapply Jobs

on:
  schedule:
    # Run every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch: # Allow manual triggering
  push:
    branches: [ main ]
    paths:
      - '.github/scripts/job-fetcher/**'
      - '.github/scripts/real-career-scraper.js'
      - '.github/scripts/enhanced-discord-bot.js'

# Prevent concurrent runs to avoid git conflicts
concurrency:
  group: repo-commits-${{ github.repository }}
  cancel-in-progress: false  # Don't cancel, wait for previous to finish

jobs:
  update-jobs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for proper rebasing
        token: ${{ secrets.GITHUB_TOKEN }}  # Use default token for pushing
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
        
    - name: Install scraper dependencies
      working-directory: jobboard
      run: npm install puppeteer
      
    - name: Update job listings
      env:
        JSEARCH_API_KEY: ${{ secrets.JSEARCH_API_KEY }}
      run: node .github/scripts/job-fetcher/index.js


    - name: Install bot dependencies
      working-directory: .github/scripts
      run: npm install discord.js@14

    - name: Post new jobs via Enhanced Bot
      run: node .github/scripts/save-discord-logs.js
      env:
        DISCORD_TOKEN:       ${{ secrets.DISCORD_TOKEN }}
        DISCORD_CHANNEL_ID:  ${{ secrets.DISCORD_CHANNEL_ID }}
        DISCORD_CLIENT_ID:   ${{ secrets.DISCORD_CLIENT_ID }}
        DISCORD_GUILD_ID:    ${{ secrets.DISCORD_GUILD_ID }}
        # Multi-channel forum configuration
        DISCORD_TECH_CHANNEL_ID:      ${{ secrets.DISCORD_TECH_CHANNEL_ID }}
        DISCORD_SALES_CHANNEL_ID:     ${{ secrets.DISCORD_SALES_CHANNEL_ID }}
        DISCORD_MARKETING_CHANNEL_ID: ${{ secrets.DISCORD_MARKETING_CHANNEL_ID }}
        DISCORD_FINANCE_CHANNEL_ID:   ${{ secrets.DISCORD_FINANCE_CHANNEL_ID }}
        DISCORD_HEALTHCARE_CHANNEL_ID: ${{ secrets.DISCORD_HEALTHCARE_CHANNEL_ID }}
        DISCORD_PRODUCT_CHANNEL_ID:   ${{ secrets.DISCORD_PRODUCT_CHANNEL_ID }}
        DISCORD_SUPPLY_CHANNEL_ID:    ${{ secrets.DISCORD_SUPPLY_CHANNEL_ID }}
        DISCORD_PM_CHANNEL_ID:         ${{ secrets.DISCORD_PM_CHANNEL_ID }}
        DISCORD_HR_CHANNEL_ID:         ${{ secrets.DISCORD_HR_CHANNEL_ID }}

    - name: Save Discord bot logs
      if: always()  # Always save logs, even if bot fails
      run: |
        # Check if logs were created
        if [ -d ".github/logs" ]; then
          echo "📁 Discord bot logs found, preparing to save..."

          # Add logs to git (but not in main history)
          git add .github/logs/

          # Also create a summary of the latest log
          if [ -f ".github/logs/latest.log" ]; then
            echo "📄 Latest log summary:"
            tail -50 .github/logs/latest.log
          fi
        else
          echo "📭 No Discord bot logs found"
        fi

    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
          echo "Found changes in files"
        else
          echo "changed=false" >> $GITHUB_OUTPUT
          echo "No changes detected"
        fi
      
    - name: Commit and Push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "team@zapply.ai"
        git config --local user.name "Zapply Team"

        # Pull latest changes BEFORE committing
        echo "Pulling latest changes before commit..."
        git pull origin main --no-edit || echo "No remote changes to pull"

        # Now add and commit our changes
        git add -A

        # Get job count from README for commit message
        JOB_COUNT=$(grep -o "Active Positions\*\*: [0-9]*" README.md | grep -o "[0-9]*" || echo "0")
        COMPANY_COUNT=$(grep -o "Companies\*\*: [0-9]*" README.md | grep -o "[0-9]*" || echo "0")

        git commit -m "Update jobs - $(date +'%Y-%m-%d')

        Found $JOB_COUNT positions from $COMPANY_COUNT companies
        Updated categories, locations, and experience levels
        Next update tomorrow"

        # Push with retry
        echo "Pushing changes..."
        for i in 1 2 3; do
          echo "Push attempt $i of 3..."
          if git push origin main; then
            echo "✅ Successfully pushed changes!"
            break
          else
            echo "Push failed, pulling and retrying..."
            git pull origin main --rebase --autostash || git pull origin main --no-edit
            sleep 5
          fi
        done
        
    - name: Create job summary
      run: |
        echo "## 🚀 Zapply Jobs Updated!" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [ "${{ steps.verify-changed-files.outputs.changed }}" == "true" ]; then
          # Extract stats from README
          JOB_COUNT=$(grep -o "Active Positions\*\*: [0-9]*" README.md | grep -o "[0-9]*" || echo "0")
          COMPANY_COUNT=$(grep -o "Companies\*\*: [0-9]*" README.md | grep -o "[0-9]*" || echo "0")
          FAANG_COUNT=$(grep -o "FAANG+ Jobs\*\*: [0-9]*" README.md | grep -o "[0-9]*" || echo "0")
          
          echo "✅ **Successfully updated job board with fresh opportunities**" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 📊 Today's Haul:" >> $GITHUB_STEP_SUMMARY  
          echo "- 🎯 **$JOB_COUNT total positions** from elite tech companies" >> $GITHUB_STEP_SUMMARY
          echo "- 🏢 **$COMPANY_COUNT companies** tracked (FAANG, unicorns, startups)" >> $GITHUB_STEP_SUMMARY
          echo "- ⭐ **$FAANG_COUNT FAANG+ jobs** from top-tier companies" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 🔍 Search Coverage:" >> $GITHUB_STEP_SUMMARY
          echo "- 🌐 **Multi-location search**: SF Bay Area, NYC, Seattle, Austin, Remote" >> $GITHUB_STEP_SUMMARY
          echo "- 🎓 **All experience levels**: Entry-level to Senior positions" >> $GITHUB_STEP_SUMMARY
          echo "- 💼 **10+ role categories**: SWE, ML/AI, Data, Mobile, DevOps, Product, Design" >> $GITHUB_STEP_SUMMARY
          echo "- 🏆 **Elite companies only**: FAANG, unicorns, top startups, gaming leaders" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 🎯 Quality Filters Applied:" >> $GITHUB_STEP_SUMMARY
          echo "- ✨ Removed duplicates and spam postings" >> $GITHUB_STEP_SUMMARY
          echo "- 🏢 Normalized company names and subsidiaries" >> $GITHUB_STEP_SUMMARY  
          echo "- 📊 Ranked by company tier (FAANG first)" >> $GITHUB_STEP_SUMMARY
          echo "- 🔗 Verified direct application links" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**🔄 Next update**: Tomorrow at 9 AM UTC" >> $GITHUB_STEP_SUMMARY
        else
          echo "ℹ️ **No new opportunities found - job board is current**" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "All tracked companies have been checked for new postings." >> $GITHUB_STEP_SUMMARY
          echo "The existing job listings are still fresh and active." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**🔄 Next check**: Tomorrow at 9 AM UTC" >> $GITHUB_STEP_SUMMARY
        fi
