name: Weekly GitHub Summary to Discord

on:
  schedule:
    # Runs at 6:00 AM London time (GMT/BST) every Monday
    # London = UTC+0 (winter) or UTC+1 (summer DST)
    # Using 6 AM UTC = 6 AM GMT (winter) / 7 AM BST (summer)
    - cron: '0 6 * * 1'
  workflow_dispatch: # Allow manual triggers for testing

jobs:
  post-weekly-summary:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to commit data files

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install @octokit/rest node-fetch

      - name: Fetch and post weekly summary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          ORG_NAME: 'zapplyjobs'
        run: node .github/scripts/weekly-summary.js

      - name: Commit updated data
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .github/data/weekly-stats.json
          git diff --staged --quiet || git commit -m "Update weekly stats data [skip ci]"
          git pull --rebase origin main
          git push
